version: '3'

# context: 빌드명령을 실행할 경로
# dockerfile: 빌드를 실행할 파일
# expose: 같은 네트워크에서 접근시 사용할 포트
# ports: 호스트에서:같은네트워크
# env_file: 환경변수가 저장되있는 파일
# volumes: 컨테이너에 마운트할 볼륨 경로 host::container
# depends_on: 종속성 순서대로 실행될 수 있도록 설정
# driver: 볼륨에 사용할 볼륨 드라이버
# driver_opts: 볼륨 드라이버에 전달할 옵션 목록
# (type: 사용할 볼륨 드라이버 유형, device: 호스트 파일 시스템에서 사용할 경로, o: 마운트 옵션)

services:
#        build:
#    nginx:
#            context: ./requierments/nginx
#            dockerfile: ./Dockerfile
#        volumes:
#            - wp:/var/www/html
#        ports:
#            - "443:443"
#        networks:
#            - intra
#        depends_on:
#            - wordpress
#        env_file:
#            - .env
#        restart: always

    mariadb:
        build:
            context: ./requierments/mariadb
            dockerfile: ./Dockerfile
        networks:
            - intra
        volumes:
            - db:/var/lib/mysql
        env_file:
            - .env
        restart: always

#    wordpress:
#        build:
#            context: ./requierments/wordpress
#            dockerfile: ./Dockerfile
#        depends_on:
#            - mariadb
#        volumes:
#            - wp:/var/www/html
#        networks:
#            - intra
#        restart: always

volumes:
    wp:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: 'home/jaeyjeon/data/wordpress'

    db:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: 'home/jaeyjeon/data/mariadb'

networks:
    intra:
        driver: bridge
