ALTER USER 'root'@'localhost' IDENTIFIED BY 'root12345';
FLUSH PRIVILEGES
CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'jaeyjeon'@'%' IDENTIFIED BY '12345';
GRANT ALL PRIVILEGES ON wordpress.* TO 'jaeyjeon'@'%';
FLUSH PRIVILEGES
