CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'jaeyjeon'@'%' IDENTIFIED BY '1q2w3e4r';
GRANT ALL PRIVILEGES ON wordpress.* TO 'jaeyjeon'@'%';
FLUSH PRIVILEGES
ALTER USER 'root'@'loaclhost' IDENTFIED BY 'root1q2w3e4r';
FLUSH PRIVILEGES
